[package]
name = "tauri"
version = "0.1.3"
authors = ["Lucas Fernandes Gonçalves Nogueira <lucas@quasar.dev>", "Daniel Thompson-Yvetot <denjell@sfosc.org>"]
license = "MIT"
homepage = "https://tauri-apps.org"
repository = "https://github.com/tauri-apps/tauri"
description = "Make tiny, secure apps for all desktop platforms with Tauri"
edition = "2018"

[dependencies]
web-view = "0.5.4"
serde_json = "1.0.42"
serde = "1.0"
serde_derive = "1.0"
dirs = "2.0.2"
ignore = "0.4.10"
phf = "0.7.24"
threadpool = "1.7"
rand = "0.7"
reqwest = "0.9"
pbr = "1"
zip = "0.5.3"
tempdir = "0.3"
semver = "0.9"
tempfile = "3"
either = "1.5.3"
tar = "0.4"
flate2 = "1"
hyper-old-types = "0.11.0"
sysinfo = "0.9"
webbrowser = "0.5.2"
uuid = { version = "0.8.1", features = ["v4"] }
lazy_static = "1.4.0"
includedir = "0.5.0"
tiny_http = "0.6"
clap = {version = "2.33", features = ["yaml"]}

[build-dependencies]
includedir_codegen = "0.5.0"

[features]
edge = ["web-view/edge"]
dev = []
embedded-server = []
all-api = []
readTextFile = []
readBinaryFile = []
writeFile = []
listFiles = []
listDirs = []
setTitle = []
execute = []
open = []
emit = []
