[package]
name = "tauri-api"
version = "0.5.2"
authors = ["Lucas Fernandes Gonçalves Nogueira <lucas@tauri.studio>", "Daniel Thompson-Yvetot <denjell@sfosc.org>", "Tensor Programming <tensordeveloper@gmail.com>"]
license = "MIT"
homepage = "https://tauri.studio"
repository = "https://github.com/tauri-apps/tauri"
description = "Make tiny, secure apps for all desktop platforms with Tauri"
edition = "2018"
exclude = ["test/fixture/**"]

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_repr = "0.1"
dirs = "2.0.2"
ignore = "0.4.16"
zip = "0.5.5"
tempdir = "0.3"
semver = "0.10"
tempfile = "3"
either = "1.5.3"
tar = "0.4"
flate2 = "1"
anyhow = "1.0.31"
thiserror = "1.0.19"
rand = "0.7"
nfd = "0.0.4"
tauri-dialog = { git = "https://github.com/tauri-apps/tauri-dialog-rs", version = "0.1" }
attohttpc = {version = "0.14.0", features=["json", "form" ]}
http = "0.2"
tauri-utils = {version = "0.5", path = "../tauri-utils"}
envmnt = "0.8.2"
clap = { git = "https://github.com/clap-rs/clap", rev = "1a276f8", version = "3.0.0-beta.1", optional = true }
notify-rust = { version = "4.0.0-beta.4", optional = true }

[dev-dependencies]
quickcheck = "0.9.2"
quickcheck_macros = "0.9.1"
totems = "0.2.7"

[features]
cli = ["clap"]
notification = ["notify-rust"]
