[workspace]
members = [
  # core
  "core/tauri",
  "core/tauri-runtime",
  "core/tauri-runtime-wry",
  "core/tauri-macros",
  "core/tauri-utils",
  "core/tauri-build",
  "core/tauri-codegen",
  "core/tauri-config-schema",

  # integration tests
  "core/tests/restart",
  "core/tests/tauri-codegen-test",

  # examples that only require Cargo
  "examples/commands",
  "examples/helloworld",
  "examples/isolation",
  "examples/multiwindow",
  "examples/navigation",
  "examples/parent-window",
  "examples/splashscreen",
  "examples/state",
  "examples/streaming",
  #"examples/tauri-dynamic-lib",
]

exclude = [
  # examples that require NodeJS and/or NPM
  "examples/api/src-tauri",
  "examples/resources/src-tauri",
  "examples/sidecar/src-tauri",
  "examples/web/core",
  "examples/workspace",
]

[workspace.package]
authors = [ "Tauri Programme within The Commons Conservancy" ]
homepage = "https://tauri.app/"
repository = "https://github.com/tauri-apps/tauri"
categories = [ "gui", "web-programming" ]
license = "Apache-2.0 OR MIT"
edition = "2021"
rust-version = "1.65"

# default to small, optimized workspace release binaries
[profile.release]
panic = "abort"
codegen-units = 1
lto = true
incremental = false
opt-level = "s"
