[workspace]
members = [
  # core
  "core/tauri",
  "core/tauri-runtime",
  "core/tauri-runtime-wry",
  "core/tauri-macros",
  "core/tauri-utils",
  "core/tauri-build",
  "core/tauri-codegen",
  "core/config-schema",

  # integration tests
  "core/tests/restart",
  "core/tests/app-updater"
]

exclude = [
  # examples that can be compiled with the tauri CLI
  "examples/api/src-tauri",
  "examples/updater/src-tauri",
  "examples/resources/src-tauri",
  "examples/sidecar/src-tauri",
  "examples/web/core",
  "examples/workspace"
]

[workspace.dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
anyhow = "1.0"
glob = "0.3"
tempfile = "3.3"
thiserror = "1.0"
brotli = { version = "3", default-features = false, features = [ "std" ] }
url = { version = "2.3", features = [ "serde" ] }

# default to small, optimized workspace release binaries
[profile.release]
panic = "abort"
codegen-units = 1
lto = true
incremental = false
opt-level = "s"
