[workspace]
members = [
  "tauri",
  "tauri-api",
  "tauri-macros",
  "tauri-utils",

  # core
  "core/tauri-build",
  "core/tauri-codegen",

  # examples
  "examples/api/src-tauri",
  "examples/helloworld/src-tauri",
  "examples/multiwindow/src-tauri",
]

[patch.crates-io]
wry = { git = "https://github.com/tauri-apps/wry", branch = "feat/file-drop-window-proxy" }

# default to small, optimized workspace release binaries
[profile.release]
panic = "abort"
codegen-units = 1
lto = true
incremental = false
opt-level = "s"
