[workspace]
members = [
  # core
  "core/tauri",
  "core/tauri-runtime",
  "core/tauri-runtime-wry",
  "core/tauri-macros",
  "core/tauri-utils",
  "core/tauri-build",
  "core/tauri-codegen",

  # examples
  "examples/api/src-tauri",
  "examples/commands/src-tauri",
  "examples/helloworld/src-tauri",
  "examples/multiwindow/src-tauri",
  "examples/navigation/src-tauri",
  "examples/params/src-tauri",
  "examples/splashscreen/src-tauri",
  "examples/state/src-tauri",
  "examples/sidecar/src-tauri",
  # used to build updater artifacts
  "examples/updater/src-tauri",
]

[patch.crates-io]
tao = { git = "https://github.com/tauri-apps/tao", rev = "66360eea4ec6af8a52afcebb7700f486a0092168" }

# default to small, optimized workspace release binaries
[profile.release]
panic = "abort"
codegen-units = 1
lto = true
incremental = false
opt-level = "s"
