[workspace]
members = [
  # core
  "core/tauri",
  "core/tauri-runtime",
  "core/tauri-runtime-wry",
  "core/tauri-macros",
  "core/tauri-utils",
  "core/tauri-build",
  "core/tauri-codegen",
  "core/tauri-config-schema",

  # integration tests
  "core/tests/restart",
  "core/tests/app-updater",
]

exclude = [
  # examples that can be compiled with the tauri CLI
  "examples/api/src-tauri",
  "examples/updater/src-tauri",
  "examples/resources/src-tauri",
  "examples/sidecar/src-tauri",
  "examples/web/core",
  "examples/file-associations/src-tauri",
  "examples/workspace",
]

# default to small, optimized workspace release binaries
[profile.release]
panic = "abort"
codegen-units = 1
lto = true
incremental = false
opt-level = "s"

[patch.crates-io]
tao = { git = "https://github.com/meowtec/tao/", branch = "feat-open-file" }
