[package]
name = "tauri-runtime-wry"
version = "0.0.0"
authors = [ "Tauri Programme within The Commons Conservancy" ]
categories = [ "gui", "web-programming" ]
license = "Apache-2.0 OR MIT"
homepage = "https://tauri.studio"
repository = "https://github.com/tauri-apps/tauri"
description = "Wry bindings to the Tauri runtime"
edition = "2018"

[dependencies]
wry = { version = "0.9.2", default-features = false, features = ["file-drop", "protocol", "win32"] }
tauri-runtime = { version = "0.0.0", path = "../tauri-runtime" }
tauri-utils = { version = "1.0.0-beta-rc.1", path = "../tauri-utils" }
image = "0.23"
uuid = { version = "0.8.2", features = [ "v4" ] }

[features]
dox = [ "wry/dox" ]
menu = [ "wry/menu" ]
system-tray = [ "wry/tray" ]
