[package]
name = "app"
version = "0.1.0"
description = "A Tauri App"
author = ["you"]
license = ""
repository = ""
default-run = "app"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tauri-ui = { path = "../node_modules/@tauri-apps/tauri/bindings/rust" }
serde_json = "1.0.39"
serde = "1.0"
serde_derive = "1.0"
tiny_http = "0.6"
phf = "0.7.21"
includedir = "0.5.0"
tauri = { path = "../node_modules/@tauri-apps/tauri/lib/rust" }

[features]
dev = ["tauri/dev"] # has no explicit dependencies
embedded-server = ["tauri/embedded-server"] # has no explicit dependencies

[package.metadata.bundle]
identifier = "com.tauri.dev"
icon = ["icons/32x32.png", "icons/128x128.png", "icons/128x128@2x.png", "icons/icon.icns", "icons/icon.ico"]

[[bin]]
name = "updater"
path = "src/updater.rs"

[[bin]]
name = "app"
path = "src/main.rs"
