[package]
name = "app"
version = "0.1.0"
description = "A Quasar Tauri App"
author = []
license = ""
repository = ""
build = "build.rs"
include = ["data"]
default-run = "app"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tauri-ui = { path = "../../tauri/bindings/rust" }
serde_json = "1.0.39"
serde = "1.0"
serde_derive = "1.0"
tiny_http = "0.6"
clap = {version = "2.33", features = ["yaml"]}
phf = "0.7.21"
includedir = "0.5.0"
tauri = { path = "../../tauri/lib/rust" }

[build-dependencies]
includedir_codegen = "0.5.0"

[features]
dev = [] # has no explicit dependencies
serverless = [] # has no explicit dependencies

[package.metadata.bundle]
identifier = "com.quasar.dev"
icon = ["icons/32x32.png", "icons/128x128.png", "icons/128x128@2x.png", "icons/icon.icns", "icons/icon.ico"]

[[bin]]
name = "updater"
path = "src/updater.rs"

[[bin]]
name = "app"
path = "src/main.rs"
