[package]
name = "tauri-build"
version = "0.1.0"
authors = [
  "Lucas Fernandes Gonçalves Nogueira <lucas@tauri.studio>",
  "Daniel Thompson-Yvetot <denjell@sfosc.org>",
  "Tensor Programming <tensordeveloper@gmail.com>"
]
categories = [ "gui", "web-programming" ]
license = "MIT"
homepage = "https://tauri.studio"
repository = "https://github.com/tauri-apps/tauri/tree/dev/core/tauri-build"
description = "build time code to pair with https://crates.io/crates/tauri"
edition = "2018"

[dependencies]
anyhow = "1"

# context dependencies
proc-macro2 = "1"
quote = "1"
tauri-codegen = { path = "../tauri-codegen", optional = true }

[target."cfg(windows)".dependencies]
winres = "0.1"

[features]
# keep context non-default to prevent some relatively large deps being pulled
codegen = ["tauri-codegen"]

# enable feature flags on https://docs.rs/tauri-build
[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "doc_cfg"]
