[package]
name = "helloworld"
version = "0.1.0"
edition = "2021"

[build-dependencies]
tauri-build = { path = "../../core/tauri-build" }

[dependencies]
tauri = { path = "../../core/tauri" }
tauri-utils = { path = "../../core/tauri-utils" }
