[package]
name = "api"
version = "0.1.0"
description = "An example Tauri Application showcasing the api"
edition = "2021"
rust-version = "1.64"
license = "Apache-2.0 OR MIT"

[lib]
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { path = "../../../core/tauri-build", features = ["codegen", "isolation"] }

[dependencies]
serde_json = "1.0"
serde = { version = "1.0", features = [ "derive" ] }
tiny_http = "0.11"
log = "0.4"
#tauri-plugin-log = { git = "https://github.com/tauri-apps/plugins-workspace", branch = "next" }
tauri-plugin-sample = { path = "./tauri-plugin-sample/" }
tauri-plugin-cli = { git = "https://github.com/tauri-apps/plugins-workspace", branch = "next" }

[patch.crates-io]
tauri = { path = "../../../core/tauri" }
tauri-build = { path = "../../../core/tauri-build" }

[dependencies.tauri]
path = "../../../core/tauri"
features = [
  "api-all",
  "global-shortcut",
  "http-multipart",
  "icon-ico",
  "icon-png",
  "isolation",
  "macos-private-api",
  "windows7-compat",
  "system-tray",
  "updater"
]

[target."cfg(target_os = \"windows\")".dependencies]
window-shadows= "0.2"

[features]
custom-protocol = [ "tauri/custom-protocol" ]

# default to small, optimized release binaries
[profile.release]
panic = "abort"
codegen-units = 1
lto = true
incremental = false
opt-level = "s"
