[package]
name = "params"
version = "0.1.0"
description = "A simple Tauri Application showcasing custom Params types"
edition = "2018"

[build-dependencies]
tauri-build = { path = "../../../core/tauri-build", features = [ "codegen" ] }

[dependencies]
serde = { version = "1", features = [ "derive" ] }
tauri = { path = "../../../core/tauri", features = ["api-all"] }

[features]
default = [ "custom-protocol" ]
custom-protocol = [ "tauri/custom-protocol" ]
