[package]
name = "proton-sys"
version = "0.1.0"
authors = ["Boscop", "rstoenescu", "nothingismagick", "lucasfernog"]
license = "MIT"
repository = "https://github.com/quasarframework/proton"
description = "Rust native ffi bindings for proton UI"
keywords = ["quasar", "web", "gui", "desktop", "webkit"]
categories = ["quasar", "gui", "web-programming", "api-bindings", "rendering", "visualization"]
build = "build.rs"
links = "proton"

[lib]
name = "proton_sys"
path = "lib.rs"

[dependencies]
bitflags = "1.0"

[build-dependencies]
cc = "1"
pkg-config = "0.3"