# Copyright 2019-2022 Tauri Programme within The Commons Conservancy
# SPDX-License-Identifier: Apache-2.0
# SPDX-License-Identifier: MIT

name: Check generated files

on:
  pull_request:
    paths:
      - '.github/workflows/check-generated-files.yml'
      - 'tooling/api/**'
      - 'core/tauri/scripts/bundle.global.js'
      - 'core/tauri-utils/src/config.rs'
      - 'tooling/cli/schema.json'
      - 'core/config-schema/schema.json'
  push:
    paths:
      - '.github/workflows/check-generated-files.yml'
      - 'tooling/api/**'
      - 'core/tauri/scripts/bundle.global.js'
      - 'core/tauri-utils/src/config.rs'
      - 'tooling/cli/schema.json'
      - 'core/config-schema/schema.json'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      bundle: ${{ steps.filter.outputs.bundle }}
      schema: ${{ steps.filter.outputs.schema }}
    steps:
      - uses: actions/checkout@v2
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            bundle:
              - 'tooling/api/**'
              - 'core/tauri/scripts/bundle.global.js'
            rust-schema:
              - 'core/tauri-utils/src/config.rs'
              - 'tooling/cli/schema.json'
              - 'core/config-schema/schema.json'
            js-schema:
              - 'tooling/api/**'
              - 'tooling/api/docs/js-api.json'

  check-bundle:
    runs-on: ubuntu-latest
    needs: changes
    if: needs.changes.outputs.bundle == 'true'
    steps:
      - uses: actions/checkout@v2
      - name: generate bundle
        working-directory: tooling/api
        run: yarn && yarn build
      - name: check bundle
        run: ./.scripts/ci/has-diff.sh

  check-rust-schema:
    runs-on: ubuntu-latest
    needs: changes
    if: needs.changes.outputs.rust-schema == 'true'
    steps:
      - uses: actions/checkout@v2
      - name: install stable
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: install Linux dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev
      - uses: Swatinem/rust-cache@v2
        with:
          workspaces: core -> ../target
      - name: generate schema.json
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --manifest-path ./core/config-schema/Cargo.toml
      - name: check schema
        run: ./.scripts/ci/has-diff.sh

  check-js-schema:
    runs-on: ubuntu-latest
    needs: changes
    if: needs.changes.outputs.js-schema == 'true'
    steps:
      - uses: actions/setup-node@v3
        with:
          cache: 'yarn'
          cache-dependency-path: tooling/api/yarn.lock
      - name: Setup yarn
        working-directory: tooling/api
        run: yarn install --frozen-lockfile && yarn generate-docs
      - name: check schema
        run: ./.scripts/ci/has-diff.sh
