# Copyright 2019-2023 Tauri Programme within The Commons Conservancy
# SPDX-License-Identifier: Apache-2.0
# SPDX-License-Identifier: MIT

name: covector version or publish

on:
  push:
    branches:
      - ci/version-or-publish

jobs:
  generate-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v3

      - name: set matrix
        id: set-matrix
        shell: bash
        run: |
          OUT="$(node .scripts/test.js')"
          echo "matrix=$OUT" >> $GITHUB_OUTPUT

  version-or-publish:
    needs: generate-matrix
    runs-on: ubuntu-latest
    timeout-minutes: 65

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v2
        with:
          node-version: 14
          registry-url: 'https://registry.npmjs.org'
          cache: yarn
          cache-dependency-path: tooling/*/yarn.lock
      - run: |
        echo "${{ fromJson(needs.generate-matrix.outputs.matrix)['-tauri-apps-api']}}"
