name: test library

on: pull_request

jobs:
  build-tauri:
    runs-on: ${{ matrix.platform }}

    strategy:
      fail-fast: false
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]

    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 3
    - name: install stable
      uses: actions-rs/toolchain@v1
      with:
          toolchain: stable
    - name: build
      run: |
           cd ./tauri
           cargo build

  build-tauri-cli:
    runs-on: ${{ matrix.platform }}

    strategy:
      fail-fast: false
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]

    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 3
    - name: install stable
      uses: actions-rs/toolchain@v1
      with:
          toolchain: stable
    - name: build
      run: |
           cd ./cli/tauri-cli
           cargo build

  test-tauri-js:
    runs-on: ${{ matrix.platform }}

    strategy:
      fail-fast: false
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]

    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 3
    - name: test
      timeout-minutes: 15
      run: |
           cd ./cli/tauri.js
           yarn
           yarn test
